spring:
  cloud:
    alicloud:
      access-key: LTAI4G1ftyNGznEBecjMAhnH
      secret-key: VzFx2o6mYRqGsRGgxGtcwCls5NhD7I
      bucket: gulimall-aa
      oss:
        endpoint: oss-cn-shenzhen.aliyuncs.com
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-third-party
server:
  port: 30000

